//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferralApp.ServiceReference1.OrderPhotoPrint))]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Coupon CouponField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.OrderStatus OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ReferralApp.ServiceReference1.ProductCategory> ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToAddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToAddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToTownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ShippingCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Coupon Coupon {
            get {
                return this.CouponField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponField, value) != true)) {
                    this.CouponField = value;
                    this.RaisePropertyChanged("Coupon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.OrderStatus OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ReferralApp.ServiceReference1.ProductCategory> ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((this.ProductCategoryField.Equals(value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToAddressLine1 {
            get {
                return this.ShipToAddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToAddressLine1Field, value) != true)) {
                    this.ShipToAddressLine1Field = value;
                    this.RaisePropertyChanged("ShipToAddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToAddressLine2 {
            get {
                return this.ShipToAddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToAddressLine2Field, value) != true)) {
                    this.ShipToAddressLine2Field = value;
                    this.RaisePropertyChanged("ShipToAddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCountry {
            get {
                return this.ShipToCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToCountryField, value) != true)) {
                    this.ShipToCountryField = value;
                    this.RaisePropertyChanged("ShipToCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCounty {
            get {
                return this.ShipToCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToCountyField, value) != true)) {
                    this.ShipToCountyField = value;
                    this.RaisePropertyChanged("ShipToCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToName {
            get {
                return this.ShipToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToNameField, value) != true)) {
                    this.ShipToNameField = value;
                    this.RaisePropertyChanged("ShipToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToPostCode {
            get {
                return this.ShipToPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToPostCodeField, value) != true)) {
                    this.ShipToPostCodeField = value;
                    this.RaisePropertyChanged("ShipToPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToTownCity {
            get {
                return this.ShipToTownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToTownCityField, value) != true)) {
                    this.ShipToTownCityField = value;
                    this.RaisePropertyChanged("ShipToTownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ShippingCost {
            get {
                return this.ShippingCostField;
            }
            set {
                if ((this.ShippingCostField.Equals(value) != true)) {
                    this.ShippingCostField = value;
                    this.RaisePropertyChanged("ShippingCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceDevice {
            get {
                return this.SourceDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceDeviceField, value) != true)) {
                    this.SourceDeviceField = value;
                    this.RaisePropertyChanged("SourceDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((this.TaxField.Equals(value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coupon", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class Coupon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CouponIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.CouponUsage[] CouponUsagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FreeShippingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CouponId {
            get {
                return this.CouponIdField;
            }
            set {
                if ((this.CouponIdField.Equals(value) != true)) {
                    this.CouponIdField = value;
                    this.RaisePropertyChanged("CouponId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.CouponUsage[] CouponUsages {
            get {
                return this.CouponUsagesField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponUsagesField, value) != true)) {
                    this.CouponUsagesField = value;
                    this.RaisePropertyChanged("CouponUsages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FreeShipping {
            get {
                return this.FreeShippingField;
            }
            set {
                if ((this.FreeShippingField.Equals(value) != true)) {
                    this.FreeShippingField = value;
                    this.RaisePropertyChanged("FreeShipping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityTownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.CouponUsage[] CouponUsagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAdddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.CustomerStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityTown {
            get {
                return this.CityTownField;
            }
            set {
                if ((object.ReferenceEquals(this.CityTownField, value) != true)) {
                    this.CityTownField = value;
                    this.RaisePropertyChanged("CityTown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.CouponUsage[] CouponUsages {
            get {
                return this.CouponUsagesField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponUsagesField, value) != true)) {
                    this.CouponUsagesField = value;
                    this.RaisePropertyChanged("CouponUsages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAdddress {
            get {
                return this.EmailAdddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAdddressField, value) != true)) {
                    this.EmailAdddressField = value;
                    this.RaisePropertyChanged("EmailAdddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.CustomerStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPhotoPrint", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderPhotoPrint : ReferralApp.ServiceReference1.Order {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.OrderPhotoPrintItem[] OrderItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.OrderPhotoPrintItem[] OrderItems {
            get {
                return this.OrderItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItemsField, value) != true)) {
                    this.OrderItemsField = value;
                    this.RaisePropertyChanged("OrderItems");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Common.Enums")]
    public enum OrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AwaitingPayment = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhotosDownloaded = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Printed = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategory", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Common.Enums")]
    public enum ProductCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhotoPrint = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GiftCard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhotoBook = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditPack = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPhotoPrintItem", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderPhotoPrintItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderPhotoPrintItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Photo PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintSizeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.ProductPrice ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription {
            get {
                return this.ItemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDescriptionField, value) != true)) {
                    this.ItemDescriptionField = value;
                    this.RaisePropertyChanged("ItemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderPhotoPrintItemId {
            get {
                return this.OrderPhotoPrintItemIdField;
            }
            set {
                if ((this.OrderPhotoPrintItemIdField.Equals(value) != true)) {
                    this.OrderPhotoPrintItemIdField = value;
                    this.RaisePropertyChanged("OrderPhotoPrintItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Photo Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintSizeCode {
            get {
                return this.PrintSizeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintSizeCodeField, value) != true)) {
                    this.PrintSizeCodeField = value;
                    this.RaisePropertyChanged("PrintSizeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.ProductPrice ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPriceField, value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintSizeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.ProductCategory ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.ProductPrice[] ProductPricesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Live {
            get {
                return this.LiveField;
            }
            set {
                if ((this.LiveField.Equals(value) != true)) {
                    this.LiveField = value;
                    this.RaisePropertyChanged("Live");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintSizeCode {
            get {
                return this.PrintSizeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintSizeCodeField, value) != true)) {
                    this.PrintSizeCodeField = value;
                    this.RaisePropertyChanged("PrintSizeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.ProductCategory ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((this.ProductCategoryField.Equals(value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.ProductPrice[] ProductPrices {
            get {
                return this.ProductPricesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPricesField, value) != true)) {
                    this.ProductPricesField = value;
                    this.RaisePropertyChanged("ProductPrices");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CouponUsage", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class CouponUsage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Coupon CouponField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CouponUsageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Customer CustomerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Coupon Coupon {
            get {
                return this.CouponField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponField, value) != true)) {
                    this.CouponField = value;
                    this.RaisePropertyChanged("Coupon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CouponUsageId {
            get {
                return this.CouponUsageIdField;
            }
            set {
                if ((this.CouponUsageIdField.Equals(value) != true)) {
                    this.CouponUsageIdField = value;
                    this.RaisePropertyChanged("CouponUsageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerStatus", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Common.Enums")]
    public enum CustomerStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegistrationPending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registered = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductPrice", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class ProductPrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductPriceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityThresholdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductPriceId {
            get {
                return this.ProductPriceIdField;
            }
            set {
                if ((this.ProductPriceIdField.Equals(value) != true)) {
                    this.ProductPriceIdField = value;
                    this.RaisePropertyChanged("ProductPriceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuantityThreshold {
            get {
                return this.QuantityThresholdField;
            }
            set {
                if ((this.QuantityThresholdField.Equals(value) != true)) {
                    this.QuantityThresholdField = value;
                    this.RaisePropertyChanged("QuantityThreshold");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="http://schemas.datacontract.org/2004/07/PhotoPrint.Entities")]
    [System.SerializableAttribute()]
    public partial class Photo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((this.PhotoIdField.Equals(value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoSource {
            get {
                return this.PhotoSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoSourceField, value) != true)) {
                    this.PhotoSourceField = value;
                    this.RaisePropertyChanged("PhotoSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbUrl {
            get {
                return this.ThumbUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbUrlField, value) != true)) {
                    this.ThumbUrlField = value;
                    this.RaisePropertyChanged("ThumbUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GreetingCardDto", Namespace="http://schemas.datacontract.org/2004/07/FotoStore.AdminService.Dto")]
    [System.SerializableAttribute()]
    public partial class GreetingCardDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GreetingCardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.OrderDto OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GreetingCardId {
            get {
                return this.GreetingCardIdField;
            }
            set {
                if ((this.GreetingCardIdField.Equals(value) != true)) {
                    this.GreetingCardIdField = value;
                    this.RaisePropertyChanged("GreetingCardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.OrderDto Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://schemas.datacontract.org/2004/07/FotoStore.AdminService.Dto")]
    [System.SerializableAttribute()]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CouponIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.OrderStatus OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReferralApp.ServiceReference1.ProductCategory ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToAddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToAddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToTownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ShippingCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceDeviceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CouponId {
            get {
                return this.CouponIdField;
            }
            set {
                if ((this.CouponIdField.Equals(value) != true)) {
                    this.CouponIdField = value;
                    this.RaisePropertyChanged("CouponId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderPrice {
            get {
                return this.OrderPriceField;
            }
            set {
                if ((this.OrderPriceField.Equals(value) != true)) {
                    this.OrderPriceField = value;
                    this.RaisePropertyChanged("OrderPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.OrderStatus OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReferralApp.ServiceReference1.ProductCategory ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((this.ProductCategoryField.Equals(value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToAddressLine1 {
            get {
                return this.ShipToAddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToAddressLine1Field, value) != true)) {
                    this.ShipToAddressLine1Field = value;
                    this.RaisePropertyChanged("ShipToAddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToAddressLine2 {
            get {
                return this.ShipToAddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToAddressLine2Field, value) != true)) {
                    this.ShipToAddressLine2Field = value;
                    this.RaisePropertyChanged("ShipToAddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCountry {
            get {
                return this.ShipToCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToCountryField, value) != true)) {
                    this.ShipToCountryField = value;
                    this.RaisePropertyChanged("ShipToCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCounty {
            get {
                return this.ShipToCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToCountyField, value) != true)) {
                    this.ShipToCountyField = value;
                    this.RaisePropertyChanged("ShipToCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToName {
            get {
                return this.ShipToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToNameField, value) != true)) {
                    this.ShipToNameField = value;
                    this.RaisePropertyChanged("ShipToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToPostCode {
            get {
                return this.ShipToPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToPostCodeField, value) != true)) {
                    this.ShipToPostCodeField = value;
                    this.RaisePropertyChanged("ShipToPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToTownCity {
            get {
                return this.ShipToTownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToTownCityField, value) != true)) {
                    this.ShipToTownCityField = value;
                    this.RaisePropertyChanged("ShipToTownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShippingCost {
            get {
                return this.ShippingCostField;
            }
            set {
                if ((this.ShippingCostField.Equals(value) != true)) {
                    this.ShippingCostField = value;
                    this.RaisePropertyChanged("ShippingCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceDevice {
            get {
                return this.SourceDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceDeviceField, value) != true)) {
                    this.SourceDeviceField = value;
                    this.RaisePropertyChanged("SourceDevice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerSummaryDto", Namespace="http://schemas.datacontract.org/2004/07/FotoStore.AdminService.Dto")]
    [System.SerializableAttribute()]
    public partial class CustomerSummaryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetOrder", ReplyAction="http://tempuri.org/IAdmin/GetOrderResponse")]
        ReferralApp.ServiceReference1.OrderPhotoPrint GetOrder(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetOrder", ReplyAction="http://tempuri.org/IAdmin/GetOrderResponse")]
        System.Threading.Tasks.Task<ReferralApp.ServiceReference1.OrderPhotoPrint> GetOrderAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetOrders", ReplyAction="http://tempuri.org/IAdmin/GetOrdersResponse")]
        ReferralApp.ServiceReference1.OrderPhotoPrint[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetOrders", ReplyAction="http://tempuri.org/IAdmin/GetOrdersResponse")]
        System.Threading.Tasks.Task<ReferralApp.ServiceReference1.OrderPhotoPrint[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetGreetCardOrders", ReplyAction="http://tempuri.org/IAdmin/GetGreetCardOrdersResponse")]
        ReferralApp.ServiceReference1.GreetingCardDto[] GetGreetCardOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetGreetCardOrders", ReplyAction="http://tempuri.org/IAdmin/GetGreetCardOrdersResponse")]
        System.Threading.Tasks.Task<ReferralApp.ServiceReference1.GreetingCardDto[]> GetGreetCardOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/UpdateOrderStatus", ReplyAction="http://tempuri.org/IAdmin/UpdateOrderStatusResponse")]
        void UpdateOrderStatus(int orderId, ReferralApp.ServiceReference1.OrderStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/UpdateOrderStatus", ReplyAction="http://tempuri.org/IAdmin/UpdateOrderStatusResponse")]
        System.Threading.Tasks.Task UpdateOrderStatusAsync(int orderId, ReferralApp.ServiceReference1.OrderStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetOrdersToDispatch", ReplyAction="http://tempuri.org/IAdmin/GetOrdersToDispatchResponse")]
        ReferralApp.ServiceReference1.OrderPhotoPrint[] GetOrdersToDispatch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetOrdersToDispatch", ReplyAction="http://tempuri.org/IAdmin/GetOrdersToDispatchResponse")]
        System.Threading.Tasks.Task<ReferralApp.ServiceReference1.OrderPhotoPrint[]> GetOrdersToDispatchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/MarkOrderAsDispatched", ReplyAction="http://tempuri.org/IAdmin/MarkOrderAsDispatchedResponse")]
        void MarkOrderAsDispatched(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/MarkOrderAsDispatched", ReplyAction="http://tempuri.org/IAdmin/MarkOrderAsDispatchedResponse")]
        System.Threading.Tasks.Task MarkOrderAsDispatchedAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetCustomerSummary", ReplyAction="http://tempuri.org/IAdmin/GetCustomerSummaryResponse")]
        ReferralApp.ServiceReference1.CustomerSummaryDto GetCustomerSummary(int id, string authToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetCustomerSummary", ReplyAction="http://tempuri.org/IAdmin/GetCustomerSummaryResponse")]
        System.Threading.Tasks.Task<ReferralApp.ServiceReference1.CustomerSummaryDto> GetCustomerSummaryAsync(int id, string authToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : ReferralApp.ServiceReference1.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<ReferralApp.ServiceReference1.IAdmin>, ReferralApp.ServiceReference1.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReferralApp.ServiceReference1.OrderPhotoPrint GetOrder(int orderId) {
            return base.Channel.GetOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<ReferralApp.ServiceReference1.OrderPhotoPrint> GetOrderAsync(int orderId) {
            return base.Channel.GetOrderAsync(orderId);
        }
        
        public ReferralApp.ServiceReference1.OrderPhotoPrint[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<ReferralApp.ServiceReference1.OrderPhotoPrint[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public ReferralApp.ServiceReference1.GreetingCardDto[] GetGreetCardOrders() {
            return base.Channel.GetGreetCardOrders();
        }
        
        public System.Threading.Tasks.Task<ReferralApp.ServiceReference1.GreetingCardDto[]> GetGreetCardOrdersAsync() {
            return base.Channel.GetGreetCardOrdersAsync();
        }
        
        public void UpdateOrderStatus(int orderId, ReferralApp.ServiceReference1.OrderStatus status) {
            base.Channel.UpdateOrderStatus(orderId, status);
        }
        
        public System.Threading.Tasks.Task UpdateOrderStatusAsync(int orderId, ReferralApp.ServiceReference1.OrderStatus status) {
            return base.Channel.UpdateOrderStatusAsync(orderId, status);
        }
        
        public ReferralApp.ServiceReference1.OrderPhotoPrint[] GetOrdersToDispatch() {
            return base.Channel.GetOrdersToDispatch();
        }
        
        public System.Threading.Tasks.Task<ReferralApp.ServiceReference1.OrderPhotoPrint[]> GetOrdersToDispatchAsync() {
            return base.Channel.GetOrdersToDispatchAsync();
        }
        
        public void MarkOrderAsDispatched(int orderId) {
            base.Channel.MarkOrderAsDispatched(orderId);
        }
        
        public System.Threading.Tasks.Task MarkOrderAsDispatchedAsync(int orderId) {
            return base.Channel.MarkOrderAsDispatchedAsync(orderId);
        }
        
        public ReferralApp.ServiceReference1.CustomerSummaryDto GetCustomerSummary(int id, string authToken) {
            return base.Channel.GetCustomerSummary(id, authToken);
        }
        
        public System.Threading.Tasks.Task<ReferralApp.ServiceReference1.CustomerSummaryDto> GetCustomerSummaryAsync(int id, string authToken) {
            return base.Channel.GetCustomerSummaryAsync(id, authToken);
        }
    }
}
